apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenant-service.fullname" . }}-config
  labels:
    {{- include "tenant-service.labels" . | nindent 4 }}
data:
  service_account_email: {{ .Values.gcp.serviceAccountEmail | quote }}
  project_id: {{ .Values.gcp.projectId | quote }}
  backend_url: {{ .Values.backendUrl | quote }}
  identity_platform_auth_enabled: {{ .Values.identityPlatform.authEnabled | quote }}
  identity_platform_auth_primary_header: {{ .Values.identityPlatform.primaryHeader | quote }}
  identity_platform_auth_fallback_header: {{ .Values.identityPlatform.fallbackHeader | quote }}
  {{- if .Values.mongodb.enabled }}
  mongodb_connection_string: {{ .Values.mongodb.connectionString | quote }}
  mongodb_database: {{ .Values.mongodb.database | quote }}
  {{- end }}
  # SMTP Configuration
  smtp_from: {{ .Values.smtp.from | quote }}
  smtp_host: {{ .Values.smtp.host | quote }}
  smtp_port: {{ .Values.smtp.port | quote }}
  smtp_start_tls: {{ .Values.smtp.startTls | quote }}
  # GitHub Configuration
  github_repo_owner: {{ .Values.github.repository.owner | quote }}
  github_repo_name: {{ .Values.github.repository.name | quote }}
  # Tenant Configuration
  tenant_base_domain: {{ .Values.tenant.baseDomain | quote }}
  tenant_polling_interval_seconds: {{ .Values.tenant.pollingIntervalSeconds | quote }}
  tenant_environment: {{ .Values.tenant.environment | quote }}
  tenant_cluster: {{ .Values.tenant.cluster | quote }}

