apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenant-service.fullname" . }}-github-secret
  labels:
    {{- include "tenant-service.labels" . | nindent 4 }}
type: Opaque
data:
  github_token: {{ .Values.github.token | b64enc | quote }}

