apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenant-service.fullname" . }}-identity-platform-secret
  labels:
    {{- include "tenant-service.labels" . | nindent 4 }}
type: Opaque
data:
  identity_platform_api_key: {{ .Values.identityPlatform.apiKey | b64enc | quote }}
