{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
    {{- include "tenant-service.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
{{- end }}