apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenant-service.fullname" . }}-smtp-secret
  labels:
    {{- include "tenant-service.labels" . | nindent 4 }}
type: Opaque
data:
  smtp_user: {{ .Values.smtp.user | b64enc | quote }}
  smtp_password: {{ .Values.smtp.password | b64enc | quote }}

