apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.neo4jPvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.neo4jPvc.storage }}

