# This docker-compose deploys our whole application stack
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 20
  backend:
    image: ghcr.io/leotschritter/cad-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy # waits for pg to be ready (not just started)
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/mydatabase"
  frontend:
    image: ghcr.io/leotschritter/cad-frontend:latest
    container_name: frontend
    ports:
      - "5173:8080"

volumes:
  postgres_data:
