# CORS Configuration (permissive - API Gateway handles external CORS)
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,cache-control,if-modified-since
# quarkus.http.port=8084 # comment in for local development
