services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel-app-network

  firestore-emulator:
    image: mtlynch/firestore-emulator
    container_name: firestore_emulator
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8200
    ports:
      - "8200:8200"
    networks:
      - travel-app-network

  gcs-emulator:
    image: fsouza/fake-gcs-server
    container_name: gcs_emulator
    command: -scheme http -port 4443 -external-url http://localhost:4443
    ports:
      - "4443:4443"
    volumes:
      - gcs_data:/data
    networks:
      - travel-app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4443/storage/v1/b"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  gcs_data:

networks:
  travel-app-network:
    driver: bridge
