quarkus:
  datasource:
    db-kind: postgresql
    username: myuser
    password: mypassword
    jdbc:
      url: jdbc:postgresql://localhost:5432/mydatabase
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true