quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:mypassword}
    jdbc:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  google:
    cloud:
      projectId: ${PROJECT_ID:myprojectid}
    firestore:
      use-emulator: ${USE_FIRESTORE_EMULATOR:false}
      emulator-host: ${FIRESTORE_EMULATOR_HOST:localhost:8080}
    storage:
      use-emulator: ${USE_STORAGE_EMULATOR:false}
      emulator-host: ${STORAGE_EMULATOR_HOST:localhost:8080}
      bucket-name: 'tripico-comments'

# Profile-specific configurations
"%prod":
  quarkus:
    datasource:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      jdbc:
        url: ${DB_URL}
    hibernate-orm:
      database:
        generation: update
      log:
        sql: true
  google:
    cloud:
      projectId: ${PROJECT_ID}
    firestore:
      use-emulator: false
      emulator-host: ''
    storage:
      use-emulator: false
      emulator-host: ''
      bucket-name: 'tripico-comments'