# Auto-generated imports.tf
# This file was generated by smart-import.sh
# Only imports resources that actually exist in GCP

# Removed import for kubernetes_sa - service account doesn't exist, will be created fresh

import {
  to = google_secret_manager_secret.db_password
  id = "projects/graphite-plane-474510-s9/secrets/travel-backend-db-password"
}

import {
  to = google_firestore_database.database
  id = "(default)"
}

import {
  to = google_storage_bucket.app_bucket
  id = "graphite-plane-474510-s9-tripico-images"
}

import {
  to = google_sql_database_instance.main
  id = "graphite-plane-474510-s9/cad-travel-db"
}

import {
  to = google_sql_database.database
  id = "projects/graphite-plane-474510-s9/instances/cad-travel-db/databases/travel-db"
}

import {
  to = google_sql_user.user
  id = "graphite-plane-474510-s9/cad-travel-db/cad_db_user"
}

import {
  to = google_identity_platform_config.default
  id = "graphite-plane-474510-s9"
}

