#!/bin/bash
# Smart Import Generator - Checks which resources exist and creates imports.tf automatically

set -e

PROJECT_ID="graphite-plane-474510-s9"
REGION="europe-west1"

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         Smart Import Generator                                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Checking which resources exist in GCP..."
echo ""

# Create imports.tf with header
cat > imports.tf << 'EOF'
# Auto-generated imports.tf
# This file was generated by smart-import.sh
# Only imports resources that actually exist in GCP

EOF

# Check Service Account
echo "[1/8] Checking Service Account..."
if gcloud iam service-accounts describe travel-backend-sa@${PROJECT_ID}.iam.gserviceaccount.com >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_service_account.cloud_run_sa
  id = "projects/${PROJECT_ID}/serviceAccounts/travel-backend-sa@${PROJECT_ID}.iam.gserviceaccount.com"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

# Check Secret
echo "[2/8] Checking Secret Manager..."
if gcloud secrets describe travel-backend-db-password --project=${PROJECT_ID} >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_secret_manager_secret.db_password
  id = "projects/${PROJECT_ID}/secrets/travel-backend-db-password"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

# Check Firestore
echo "[3/8] Checking Firestore..."
if gcloud firestore databases describe --database="(default)" --project=${PROJECT_ID} >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_firestore_database.database
  id = "(default)"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

# Check Storage Bucket
echo "[4/8] Checking Storage Bucket..."
if gcloud storage buckets describe gs://${PROJECT_ID}-tripico-images >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_storage_bucket.app_bucket
  id = "${PROJECT_ID}-tripico-images"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

# Check Cloud SQL Instance
echo "[5/8] Checking Cloud SQL Instance..."
if gcloud sql instances describe cad-travel-db --project=${PROJECT_ID} >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_sql_database_instance.main
  id = "${PROJECT_ID}/cad-travel-db"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

# Check Cloud SQL Database
echo "[6/8] Checking Cloud SQL Database..."
if gcloud sql databases describe travel-db --instance=cad-travel-db --project=${PROJECT_ID} >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_sql_database.database
  id = "projects/${PROJECT_ID}/instances/cad-travel-db/databases/travel-db"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

# Check Cloud SQL User
echo "[7/8] Checking Cloud SQL User..."
if gcloud sql users list --instance=cad-travel-db --project=${PROJECT_ID} 2>/dev/null | grep -q "cad_db_user"; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_sql_user.user
  id = "${PROJECT_ID}/cad-travel-db/cad_db_user"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi


# Note: Skipping Artifact Registry check - create_artifact_registry=false in tfvars
# The resource is conditional and not in the config when disabled

# Check Identity Platform
echo "[8/9] Checking Identity Platform..."
if gcloud identity platform describe --project=${PROJECT_ID} >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_identity_platform_config.default
  id = "${PROJECT_ID}"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

# Check Cloud Run Service
echo "[9/9] Checking Cloud Run Service..."
if gcloud run services describe travel-backend --region=${REGION} --project=${PROJECT_ID} >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_cloud_run_v2_service.main
  id = "projects/${PROJECT_ID}/locations/${REGION}/services/travel-backend"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         ✅ imports.tf Generated!                              ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "File created: imports.tf"
echo ""
echo "This file contains import blocks only for resources that exist."
echo "Resources that don't exist will be created by Terraform."
echo ""
echo "Next: Run 'terraform apply'"
echo ""

