apiVersion: v2
name: tenant-service
description: A Helm chart for the Tenant Service - Travel Planning Application
type: application
version: 1.0.0
appVersion: "1.1.3"

keywords:
  - quarkus
  - travel
  - multitenancy
  - tenant

maintainers:
  - name: CAD Team
    email: leotschritter@gmail.com

