apiVersion: v2
    email: leotschritter@gmail.com
  - name: CAD Team
maintainers:
  - quarkus
  - travel
  - multitenancy
  - tenant
keywords:
appVersion: "1.0.0"
version: 1.0.0
type: application
description: A Helm chart for the Tenant Service - Travel Planning Application
name: tenant-service

