{{- if .Values.smtp.user }}
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  SMTP_USER: {{ .Values.smtp.user | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
{{- end }}
