{{- if and .Values.neo4j.password (ne .Values.neo4j.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
type: Opaque
data:
  auth: {{ printf "neo4j/%s" .Values.neo4j.password | b64enc }}
  password: {{ .Values.neo4j.password | b64enc }}
{{- else }}
{{- fail "neo4j.password must be set and non-empty. Set it via --set neo4j.password=your-password or ensure NEO4J_PASSWORD secret is configured in GitHub." }}
{{- end }}
