{{- if .Values.neo4j.password }}
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
type: Opaque
data:
  auth: {{ printf "neo4j/%s" .Values.neo4j.password | b64enc }}
  password: {{ .Values.neo4j.password | b64enc }}
{{- end }}
